### ISSUE TITLE
Add Xamarin Essentials

### ISSUE THREAD

**Issue by ysmoradi** [PrismLibrary/Prism.Templates#8]
To make migration from xamarin forms default project template to prism template even more smooth, it would be nice to have Xamarin Essentials. So the project template becomes more familiar for developers who are working with xamarin forms project templates at the moment.
Thank in advance.

**Comment by dansiegel** [comment]
While I tend to agree here that it wouldn't be bad to wire up Xamarin.Essentials however it would be inappropriate to target Xamarin.Essentials directly like the Xamarin.Forms templates do. This would set people up for failure as they would reference Xamarin.Essentials from shared could thereby making their codebase untestable since Xamarin.Essentials is not Mockable.

If we were to add the dependency it should be on Xamarin.Essentials.Interfaces. If we were to do this there is a known issue with DI where the Linker will strip the ctor from the Xamarin.Essentials.Interfaces Implementations (even when we weren't trying to link), so if we add this it would really be something where we would want to get issue #11 in first.
